repos:
-   repo: https://github.com/Tribler/mirrors-autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
        types: [file, python]

-   repo: https://github.com/Tribler/isort
    rev: 4.3.21-3-tribler
    hooks:
    - id: isort
      types: [file, python]

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      files: |
          (?x)(
          ^src/tribler-gui/|
          ^src/tribler-core/tribler_core/modules/metadata_store/|
          ^src/tribler-common
          )
      types: [file, python]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.3
    hooks:
    - id: flake8
      types: [file, python]
      additional_dependencies: [
              'flake8-import-order==0.18',
          ]
