# See: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
name: Upload Coverage

on:
  workflow_run:
    workflows: [ 'Coverage' ]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download coverage report
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: coverage.yml
          name: coverage_report

      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_PROJECT_TOKEN }}
          files: ./coverage.xml
